name: Compile

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: '开始部署...'
      uses: reuixiy/hugo-deploy@v1
      env:
        DEPLOY_REPO: Borber/Blog_Compiled
        DEPLOY_BRANCH: compiled
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        TZ: Asia/Shanghai
